### ISSUE TITLE
sqlxを使ってマイグレーションを行う

### ISSUE THREAD

**Issue by groovyjovy** [groovyjovy/axum-practice#1]
## 目標
- slqxを用いてマイグレーションを行う
- 適当に1対多数の関係を表現してみる
- school has may users のような関係を表現してみる

## 利用するツール群
[sqlx-cliの利用方法(公式)](https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md)

**Comment by groovyjovy** [comment]
## sqlxをインストールする
- こんな感じに打たないと、mysqlとかの拡張機能が入ってしまって重くなってしまう
``` shell
cargo install sqlx-cli --no-default-features --features postgres
```

## 環境変数に`DATABASE_URL`を登録する
- 今回はDocker, docker-compose.ymlでやっているので、こんな感じで登録
``` yml
  api:
    build: ./api
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      db:
        condition: service_healthy
    command: /bin/bash
    # command: /bin/bash -c "poetry run uvicorn src.main:app --host 0.0.0.0 --reload --reload-dir ./src"
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/poi
```

## DBを作成したり壊したりする
``` shell
sqlx database create
sqlx database drop
```

## usersテーブルを追加しようとしてみる
- これだと空のsqlファイルが作成される
``` shell
root@5fef23f4b152:/api# sqlx migrate add users
Creating migrations/20241004075123_users.sql
root@5fef23f4b152:/api# cat /api/migrations/20241004075123_users.sql 
-- Add migration script here
```

## migrateする
``` shell
sqlx migrate run
```

## migration情報を取得する
みたいな感じでやる
``` shell
sqlx migrate info --source ./migrations
```

## up, downができるようなマイグレーションファイルを作成する
- railsだと楽なのに、これは逆の分のファイルの作成しなければならない。
- **ここで注意しなければいけないのは、可逆性を持つマイグレーションか、そうでないマイグレーションを選択しなければいけないと言うこと。**
  - 一番最初に可逆でないマイグレーションファイル(`sqlx migrate add hoge`)みたいな感じでマイグレーションファイルを生成すると`sqlx migrate add -r fuga`みたいな感じで可逆なマイグレーションファイルを生成しようとしても暗黙のうちに非可逆なマイグレーションファイルが生成される。これはね、気づかないね。0.5.0版だと比較的わかりやすい。0.8.2でやっても気づきづらいとは思う。他のマイグレーションライブラリだと一般的なのかな？
- これ以降にマイグレーションファイルを生成すると、可逆性のマイグレーションファイルが生成される

``` shell
# 非可逆なマイグレーションファイルのみがある場合
sqlx add -r users
```
